Launch Training on Vertex AI Using XManager Version 0
google-research/skai pull request #104
Opened 2023-06-21 18:33 UTC by Alikerin

This changes adds a module in `src/skai/model/xm_launch_single_model_vertex.py` that allows for launching training on Vertex AI using XManager.

2023-06-28 18:34 UTC, jzxu requested changes
Thanks for creating this PR! I left a few comments, mostly about style. I'll leave the more substantive review to @jlee24

2023-06-28 18:34 UTC, jzxu commented on src/skai/model/xm_launch_single_model_vertex.py
> +    # if FLAGS.use_vizier:  # Tune hyperparameters with Vizier.
Is this commented out on purpose? If so, please delete the line.

2023-06-28 18:34 UTC, jzxu commented on src/skai/model/xm_launch_single_model_vertex.py
> +    # if FLAGS.use_vizier:
Is this commented out on purpose?

2023-06-28 18:34 UTC, jzxu commented on src/skai/model/configs/skai_two_tower_config.py
> +  return config
Can you add the last newline back? Thanks!

2023-06-28 18:34 UTC, jzxu commented on requirements.txt
> +google-cloud-aiplatform==1.26.1
Can you elaborate on why it's necessary to peg the requirement to a specific version?

2023-06-28 18:34 UTC, jzxu commented on .gitignore
Can you roll this back?

2023-06-29 18:29 UTC, jlee24 requested changes
Thanks for your great work!

2023-06-29 18:29 UTC, jlee24 commented on src/skai/model/log_metrics_callback.py
To make it possible to still use the internal XManager, can you refactor this file such that:
- log_metrics_callback.py so that it has only the class LogMetricsCallback
- Create file xmanager_external_metric_logger.py that has the external version of the logger
- Create file xmanager_internal_metric_logger.py that has the internal version of the logger (original ver)
- Import both into train_lib.py and use them conditionally based on whether user is using Dataflow or not

2023-06-29 18:29 UTC, jlee24 commented on src/skai/model/xm_utils.py
Our internal style guidelines prefer not having utils files. Since these constants/function is only used in xm_launch_single_model_vertex.py, can they be moved there?

2023-07-03 18:49 UTC, Alikerin commented on src/skai/model/log_metrics_callback.py
The `--use_dataflow` argument is not accessible during training but during preprocessing/data generation. 
What I have done is to check the executor and see if it's Vertex AI then send the result to train_lib.py so as to dynamically load the appropriate `XManagerMetricLogger` module.
Let me know if this works or you have other ideas.

2023-07-05 21:59 UTC, jzxu approved these changes

2023-07-26 22:55 UTC, jzxu approved these changes
Thank you for your contribution!

2023-07-27 15:42 UTC, merged